#!/usr/bin/env bash
# Installs copycat: links it onto PATH, installs missing deps, and wires up
# a global hotkey on whichever compositor is running — overriding whatever
# that key was already bound to. Safe to re-run any time (idempotent).
#
# Supported package managers: pacman (Arch/Omarchy), apt (Debian/Ubuntu/
#   Pop!_OS), dnf (Fedora).
# Supported hotkey backends:   Hyprland, Sway, COSMIC (Pop!_OS's compositor).
# Supported file-manager integration: Nautilus (GNOME Files) right-click
#   Scripts menu. COSMIC Files has no equivalent extension mechanism yet, so
#   there's nothing to install there — see README.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
COPYCAT_SRC="$SCRIPT_DIR/bin/copycat"
LOCAL_BIN="$HOME/.local/bin"
COPYCAT_LINK="$LOCAL_BIN/copycat"
KEYBIND="${1:-SUPER + SHIFT + V}"

log()  { echo "==> $*"; }
warn() { echo "!! $*" >&2; }

[[ -f "$COPYCAT_SRC" ]] || { echo "error: $COPYCAT_SRC not found" >&2; exit 1; }
chmod +x "$COPYCAT_SRC"

# Split "SUPER + SHIFT + V" into MOD_PARTS=(SUPER SHIFT) and KEY_PART=V.
IFS='+' read -ra _raw <<< "$KEYBIND"
MOD_PARTS=()
KEY_PART=""
for i in "${!_raw[@]}"; do
    part="$(echo "${_raw[$i]}" | xargs)"
    if (( i == ${#_raw[@]} - 1 )); then
        KEY_PART="$part"
    else
        MOD_PARTS+=("$part")
    fi
done

# ---- dependencies -----------------------------------------------------------
log "Checking dependencies..."

PKG_MGR=""
declare -A dep_pkg=()
if command -v omarchy >/dev/null 2>&1 || command -v pacman >/dev/null 2>&1; then
    PKG_MGR="pacman"
    dep_pkg=( [wl-paste]=wl-clipboard [wl-copy]=wl-clipboard [jq]=jq [notify-send]=libnotify )
elif command -v apt-get >/dev/null 2>&1; then
    PKG_MGR="apt"
    dep_pkg=( [wl-paste]=wl-clipboard [wl-copy]=wl-clipboard [jq]=jq [notify-send]=libnotify-bin )
elif command -v dnf >/dev/null 2>&1; then
    PKG_MGR="dnf"
    dep_pkg=( [wl-paste]=wl-clipboard [wl-copy]=wl-clipboard [jq]=jq [notify-send]=libnotify )
fi

missing_pkgs=()
declare -A seen
for cmd in wl-paste wl-copy jq notify-send; do
    if ! command -v "$cmd" >/dev/null 2>&1; then
        pkg="${dep_pkg[$cmd]:-$cmd}"
        [[ -n "${seen[$pkg]:-}" ]] || { missing_pkgs+=("$pkg"); seen[$pkg]=1; }
    fi
done

if ((${#missing_pkgs[@]})); then
    log "Installing missing packages: ${missing_pkgs[*]}"
    case "$PKG_MGR" in
        pacman)
            if command -v omarchy >/dev/null 2>&1; then
                omarchy pkg add "${missing_pkgs[@]}"
            else
                sudo pacman -S --needed --noconfirm "${missing_pkgs[@]}"
            fi
            ;;
        apt)
            sudo apt-get update -qq
            sudo apt-get install -y "${missing_pkgs[@]}"
            ;;
        dnf)
            sudo dnf install -y "${missing_pkgs[@]}"
            ;;
        *)
            warn "Don't know how to install packages on this system automatically."
            warn "Please install manually: ${missing_pkgs[*]}"
            ;;
    esac
else
    log "All dependencies already present."
fi

# ---- put copycat on PATH ----------------------------------------------------
log "Linking $COPYCAT_LINK -> $COPYCAT_SRC"
mkdir -p "$LOCAL_BIN"
ln -sf "$COPYCAT_SRC" "$COPYCAT_LINK"
case ":$PATH:" in
    *":$LOCAL_BIN:"*) ;;
    *) warn "$LOCAL_BIN is not on your PATH — add it to run 'copycat' directly from a shell." ;;
esac

# ---- Hyprland ----------------------------------------------------------------
configure_hyprland() {
    local bindings_file="$HOME/.config/hypr/bindings.lua"
    local begin="-- >>> copycat: managed keybind (auto-generated by install.sh, do not edit by hand) >>>"
    local end="-- <<< copycat: managed keybind <<<"

    local nospace="${KEYBIND// /}"
    local mods="${nospace%+*}"
    local key="${nospace##*+}"
    local display_keybind="${mods//+/ } + ${key}"

    local existing
    existing="$(omarchy menu keybindings --print 2>/dev/null | grep -F "$display_keybind" | grep -v -F "Paste clipboard image to file" || true)"
    if [[ -n "$existing" ]]; then
        log "$display_keybind is currently bound to:"
        echo "$existing" | sed 's/^/    /'
        log "Overriding it for copycat."
    fi

    log "Configuring Hyprland keybind ($KEYBIND -> copycat)..."
    mkdir -p "$(dirname "$bindings_file")"
    touch "$bindings_file"

    local backup="$bindings_file.bak.$(date +%s)"
    cp "$bindings_file" "$backup"

    python3 - "$bindings_file" "$begin" "$end" "$KEYBIND" "$COPYCAT_LINK" <<'PYEOF'
import sys

path, begin, end, keybind, target = sys.argv[1:6]

with open(path) as f:
    lines = f.readlines()

out = []
skipping = False
for line in lines:
    stripped = line.rstrip("\n")
    if stripped == begin:
        skipping = True
        continue
    if stripped == end:
        skipping = False
        continue
    if skipping:
        continue
    if "bin/copycat" in line or "/copycat\"" in line:
        continue
    out.append(line)

while out and out[-1].strip() == "":
    out.pop()

block = (
    f"\n{begin}\n"
    f'hl.unbind("{keybind}")\n'
    f'o.bind("{keybind}", "Paste clipboard image to file", "{target}")\n'
    f"{end}\n"
)

with open(path, "w") as f:
    f.writelines(out)
    f.write(block)
PYEOF

    log "Reloading Hyprland config..."
    hyprctl reload >/dev/null

    local errors
    errors="$(hyprctl configerrors)"
    if [[ -n "$errors" && "$errors" != "ok" ]]; then
        warn "Hyprland reported config errors, rolling back:"
        echo "$errors" >&2
        cp "$backup" "$bindings_file"
        hyprctl reload >/dev/null
        return 1
    fi
    rm -f "$backup"

    local bound
    bound="$(omarchy menu keybindings --print 2>/dev/null | grep -F "$display_keybind" || true)"
    log "Active binding: $bound"
}

# ---- Sway ---------------------------------------------------------------------
configure_sway() {
    local config_file="$HOME/.config/sway/config"
    local begin="# >>> copycat: managed keybind (auto-generated by install.sh, do not edit by hand) >>>"
    local end="# <<< copycat: managed keybind <<<"

    local sway_mods=() m
    for m in "${MOD_PARTS[@]}"; do
        case "$m" in
            SUPER) sway_mods+=("Mod4") ;;
            ALT)   sway_mods+=("Mod1") ;;
            SHIFT) sway_mods+=("Shift") ;;
            CTRL)  sway_mods+=("Ctrl") ;;
            *)     sway_mods+=("$m") ;;
        esac
    done
    local sway_key="$KEY_PART"
    [[ ${#sway_key} -eq 1 ]] && sway_key="${sway_key,,}"
    local combo
    combo=$(IFS=+; echo "${sway_mods[*]}+${sway_key}")

    log "Configuring Sway keybind ($combo -> copycat)..."
    mkdir -p "$(dirname "$config_file")"
    touch "$config_file"

    local backup="$config_file.bak.$(date +%s)"
    cp "$config_file" "$backup"

    python3 - "$config_file" "$begin" "$end" "$combo" "$COPYCAT_LINK" <<'PYEOF'
import re
import sys

path, begin, end, combo, target = sys.argv[1:6]

with open(path) as f:
    lines = f.readlines()

out = []
skipping = False
combo_re = re.compile(r"^\s*bindsym\s+" + re.escape(combo) + r"\s+exec\b", re.IGNORECASE)
for line in lines:
    stripped = line.rstrip("\n")
    if stripped == begin:
        skipping = True
        continue
    if stripped == end:
        skipping = False
        continue
    if skipping:
        continue
    if "bin/copycat" in line or combo_re.match(line):
        continue
    out.append(line)

while out and out[-1].strip() == "":
    out.pop()

block = f"\n{begin}\nbindsym {combo} exec {target}\n{end}\n"

with open(path, "w") as f:
    f.writelines(out)
    f.write(block)
PYEOF

    log "Reloading Sway config..."
    local result
    result="$(swaymsg reload 2>&1)"
    if echo "$result" | grep -q '"success": *false'; then
        warn "Sway reported a config error, rolling back:"
        echo "$result" >&2
        cp "$backup" "$config_file"
        swaymsg reload >/dev/null 2>&1 || true
        return 1
    fi
    rm -f "$backup"
    log "Active binding: bindsym $combo exec $COPYCAT_LINK"
}

# ---- COSMIC (Pop!_OS) ----------------------------------------------------------
configure_cosmic() {
    local shortcuts_file="$HOME/.config/cosmic/com.system76.CosmicSettings.Shortcuts/v1/custom"
    local begin="// >>> copycat: managed keybind (auto-generated by install.sh, do not edit by hand) >>>"
    local end="// <<< copycat: managed keybind <<<"

    local cosmic_mods=() m
    for m in "${MOD_PARTS[@]}"; do
        case "$m" in
            SUPER) cosmic_mods+=("Super") ;;
            ALT)   cosmic_mods+=("Alt") ;;
            SHIFT) cosmic_mods+=("Shift") ;;
            CTRL)  cosmic_mods+=("Ctrl") ;;
            *)     cosmic_mods+=("$m") ;;
        esac
    done
    local cosmic_key="$KEY_PART"
    [[ ${#cosmic_key} -eq 1 ]] && cosmic_key="${cosmic_key,,}"
    local mods_ron
    mods_ron=$(IFS=,; echo "${cosmic_mods[*]}")

    log "Configuring COSMIC keybind ([$mods_ron] + $cosmic_key -> copycat)..."
    mkdir -p "$(dirname "$shortcuts_file")"
    [[ -f "$shortcuts_file" ]] || printf '{\n}\n' > "$shortcuts_file"

    local backup="$shortcuts_file.bak.$(date +%s)"
    cp "$shortcuts_file" "$backup"

    python3 - "$shortcuts_file" "$begin" "$end" "$mods_ron" "$cosmic_key" "$COPYCAT_LINK" <<'PYEOF'
import re
import sys

path, begin, end, mods_ron, key, target = sys.argv[1:7]
target_mods = frozenset(m.strip() for m in mods_ron.split(",") if m.strip())
target_key = key.lower()

with open(path) as f:
    content = f.read()

# Strip our previous managed block, wherever it landed.
content = re.sub(
    re.escape(begin) + r".*?" + re.escape(end) + r"\n?",
    "",
    content,
    flags=re.DOTALL,
)

open_idx = content.find("{")
close_idx = content.rfind("}")
if open_idx == -1 or close_idx == -1:
    content = "{\n}\n"
    open_idx = content.find("{")
    close_idx = content.rfind("}")

header = content[: open_idx + 1]
body = content[open_idx + 1 : close_idx].lstrip("\n")
footer = content[close_idx:]

entry_re = re.compile(
    r'^\s*\(\s*modifiers:\s*\[(?P<mods>[^\]]*)\]\s*'
    r'(?:,\s*key:\s*"(?P<key>[^"]*)")?'
    r'(?:,\s*keycode:\s*\d+)?'
    r'(?:,\s*description:\s*"[^"]*")?'
    r'\s*\)\s*:\s*(?P<action>.*),\s*$'
)

kept_lines = []
for line in body.splitlines(keepends=True):
    m = entry_re.match(line.strip("\n"))
    if m:
        mods = frozenset(x.strip() for x in m.group("mods").split(",") if x.strip())
        k = (m.group("key") or "").lower()
        if mods == target_mods and k == target_key:
            continue  # drop conflicting/stale entry for this exact combo
    kept_lines.append(line)
body = "".join(kept_lines)

if body and not body.endswith("\n"):
    body += "\n"

entry = f'{begin}\n(modifiers: [{mods_ron}], key: "{key}"): Spawn("{target}"),\n{end}\n'
body += entry

with open(path, "w") as f:
    f.write(header + "\n" + body + footer)
PYEOF

    log "Written to $shortcuts_file"
    log "COSMIC watches this file and should pick it up live; if the hotkey"
    log "doesn't respond, log out and back in once."
    rm -f "$backup"
}

# ---- pick a hotkey backend -----------------------------------------------------
if command -v hyprctl >/dev/null 2>&1; then
    configure_hyprland || warn "Hyprland keybind setup failed; copycat is still installed as a CLI command."
elif command -v swaymsg >/dev/null 2>&1 && [[ -n "${SWAYSOCK:-}" ]]; then
    configure_sway || warn "Sway keybind setup failed; copycat is still installed as a CLI command."
elif pgrep -x cosmic-comp >/dev/null 2>&1 || [[ "${XDG_CURRENT_DESKTOP:-}" == *COSMIC* ]]; then
    configure_cosmic || warn "COSMIC keybind setup failed; copycat is still installed as a CLI command."
else
    log "No supported compositor detected (Hyprland, Sway, COSMIC) — skipping hotkey setup."
    log "copycat is installed; run it with: copycat  (or bind a key to it manually)"
fi

# ---- Nautilus "paste into this folder" right-click script ---------------------
if command -v nautilus >/dev/null 2>&1; then
    NAUTILUS_SCRIPTS_DIR="$HOME/.local/share/nautilus/scripts"
    NAUTILUS_SCRIPT_NAME="Paste Clipboard Image Here"
    log "Installing Nautilus script: $NAUTILUS_SCRIPT_NAME"
    mkdir -p "$NAUTILUS_SCRIPTS_DIR"
    install -m 755 "$SCRIPT_DIR/nautilus-scripts/$NAUTILUS_SCRIPT_NAME" \
        "$NAUTILUS_SCRIPTS_DIR/$NAUTILUS_SCRIPT_NAME"
    log "In Nautilus: right-click a folder's background -> Scripts -> $NAUTILUS_SCRIPT_NAME"
else
    log "Nautilus not found — skipping file-manager context-menu setup."
    log "(COSMIC Files has no scripting/extension hook yet, so there's nothing to wire up there.)"
fi

log "Done. Copy an image, then run 'copycat', press $KEYBIND in a supported terminal/compositor, or use the Nautilus Scripts menu."
