#!/usr/bin/env bash
# Installs copycat: links it onto PATH, installs missing deps, and wires up
# the Hyprland/Omarchy hotkey — overriding whatever that key was already
# bound to. Safe to re-run any time (idempotent).
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
COPYCAT_SRC="$SCRIPT_DIR/bin/copycat"
LOCAL_BIN="$HOME/.local/bin"
COPYCAT_LINK="$LOCAL_BIN/copycat"
BINDINGS_FILE="$HOME/.config/hypr/bindings.lua"
KEYBIND="${1:-SUPER + SHIFT + V}"
MARKER_BEGIN="-- >>> copycat: managed keybind (auto-generated by install.sh, do not edit by hand) >>>"
MARKER_END="-- <<< copycat: managed keybind <<<"

log()  { echo "==> $*"; }
warn() { echo "!! $*" >&2; }

[[ -f "$COPYCAT_SRC" ]] || { echo "error: $COPYCAT_SRC not found" >&2; exit 1; }
chmod +x "$COPYCAT_SRC"

# ---- dependencies ----------------------------------------------------------
log "Checking dependencies..."
declare -A dep_pkg=( [wl-paste]=wl-clipboard [wl-copy]=wl-clipboard [jq]=jq [notify-send]=libnotify )
missing_pkgs=()
declare -A seen
for cmd in "${!dep_pkg[@]}"; do
    if ! command -v "$cmd" >/dev/null 2>&1; then
        pkg="${dep_pkg[$cmd]}"
        [[ -n "${seen[$pkg]:-}" ]] || { missing_pkgs+=("$pkg"); seen[$pkg]=1; }
    fi
done

if ((${#missing_pkgs[@]})); then
    log "Installing missing packages: ${missing_pkgs[*]}"
    if command -v omarchy >/dev/null 2>&1; then
        omarchy pkg add "${missing_pkgs[@]}"
    elif command -v pacman >/dev/null 2>&1; then
        sudo pacman -S --needed --noconfirm "${missing_pkgs[@]}"
    else
        warn "Don't know how to install packages on this system automatically."
        warn "Please install manually: ${missing_pkgs[*]}"
    fi
else
    log "All dependencies already present."
fi

# ---- put copycat on PATH ---------------------------------------------------
log "Linking $COPYCAT_LINK -> $COPYCAT_SRC"
mkdir -p "$LOCAL_BIN"
ln -sf "$COPYCAT_SRC" "$COPYCAT_LINK"
case ":$PATH:" in
    *":$LOCAL_BIN:"*) ;;
    *) warn "$LOCAL_BIN is not on your PATH — add it to run 'copycat' directly from a shell." ;;
esac

# ---- wire up the Hyprland hotkey ------------------------------------------
if command -v hyprctl >/dev/null 2>&1; then
    # Show what the key is currently doing before we override it.
    nospace="${KEYBIND// /}"
    mods="${nospace%+*}"
    key="${nospace##*+}"
    display_keybind="${mods//+/ } + ${key}"

    existing="$(omarchy menu keybindings --print 2>/dev/null | grep -F "$display_keybind" | grep -v -F "Paste clipboard image to file" || true)"
    if [[ -n "$existing" ]]; then
        log "$display_keybind is currently bound to:"
        echo "$existing" | sed 's/^/    /'
        log "Overriding it for copycat."
    fi

    log "Configuring Hyprland keybind ($KEYBIND -> copycat)..."
    mkdir -p "$(dirname "$BINDINGS_FILE")"
    touch "$BINDINGS_FILE"

    backup="$BINDINGS_FILE.bak.$(date +%s)"
    cp "$BINDINGS_FILE" "$backup"

    python3 - "$BINDINGS_FILE" "$MARKER_BEGIN" "$MARKER_END" "$KEYBIND" "$COPYCAT_LINK" <<'PYEOF'
import sys

path, begin, end, keybind, target = sys.argv[1:6]

with open(path) as f:
    lines = f.readlines()

out = []
skipping = False
for line in lines:
    stripped = line.rstrip("\n")
    if stripped == begin:
        skipping = True
        continue
    if stripped == end:
        skipping = False
        continue
    if skipping:
        continue
    if "bin/copycat" in line or "/copycat\"" in line:
        # drop stray unmarked copycat bindings left by earlier manual edits
        continue
    out.append(line)

while out and out[-1].strip() == "":
    out.pop()

block = (
    f"\n{begin}\n"
    f'hl.unbind("{keybind}")\n'
    f'o.bind("{keybind}", "Paste clipboard image to file", "{target}")\n'
    f"{end}\n"
)

with open(path, "w") as f:
    f.writelines(out)
    f.write(block)
PYEOF

    log "Reloading Hyprland config..."
    hyprctl reload >/dev/null

    errors="$(hyprctl configerrors)"
    if [[ -n "$errors" && "$errors" != "ok" ]]; then
        warn "Hyprland reported config errors, rolling back:"
        echo "$errors" >&2
        cp "$backup" "$BINDINGS_FILE"
        hyprctl reload >/dev/null
        exit 1
    fi
    rm -f "$backup"

    bound="$(omarchy menu keybindings --print 2>/dev/null | grep -F "$display_keybind" || true)"
    log "Active binding: $bound"
else
    log "hyprctl not found — skipping hotkey setup (this step only applies to Hyprland/Omarchy)."
fi

# ---- wire up the Nautilus "paste into this folder" right-click script -----
if command -v nautilus >/dev/null 2>&1; then
    NAUTILUS_SCRIPTS_DIR="$HOME/.local/share/nautilus/scripts"
    NAUTILUS_SCRIPT_NAME="Paste Clipboard Image Here"
    log "Installing Nautilus script: $NAUTILUS_SCRIPT_NAME"
    mkdir -p "$NAUTILUS_SCRIPTS_DIR"
    install -m 755 "$SCRIPT_DIR/nautilus-scripts/$NAUTILUS_SCRIPT_NAME" \
        "$NAUTILUS_SCRIPTS_DIR/$NAUTILUS_SCRIPT_NAME"
    log "In Nautilus: right-click a folder's background -> Scripts -> $NAUTILUS_SCRIPT_NAME"
else
    log "Nautilus not found — skipping file-manager context-menu setup."
fi

log "Done. Copy an image, then run 'copycat', press $KEYBIND in a terminal, or use the Nautilus Scripts menu."
